### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DGolubets** [scalameta/metals-zed#11]
Hi,

I was playing with Zed today and tried to open my Scala project. 
But I get nothing apart from syntax coloring.

It does work correctly in VSCode.

Coursier and Metals are installed.

Zed: v0.143.6 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 31.1 GiB
Architecture: x86_64

**Comment by nightscape** [comment]
Anything interesting when you open `debug: open language server logs`?

**Comment by DGolubets** [comment]
> Anything interesting when you open `debug: open language server logs`?

They are empty..

**Comment by nightscape** [comment]
I had some issues in the beginning as well. Afair they went away after opening the project in VS Code first such that all the required `.bsp` files were in place.
How did you install Coursier and Metals?

**Comment by DGolubets** [comment]
> How did you install Coursier and Metals?

I installed Coursier via [Native Launcher](https://get-coursier.io/docs/cli-installation) method.
Then I just ran `cs install metals`.

**Comment by tgodzik** [comment]
@nightscape looks like show message request is not supported in Zed? It should show up with a prompt to import the build. You should be able to use commands from Zed to get the same results. There are at least two relevant here `metals.build-import` for just importing and `metals.bsp-switch` for importing a different build server than the default.

**Comment by SlowBrainDude** [comment]
@DGolubets, I also run into a "not working" issue. The solution for me was adding the path to `metals` in my shell launch script (in my case `.bashrc`). It seems `zed` does not pick up an exported $PATH variable from the shell environment directly. The `.bashrc` (or some other shell launch script?) entry seems to be mandatory currently.

I've opened a PR adding a note to the README about that behavior.

@tgodzik, @nightscape the "import build" dialog showed up for me right now in `zed` when opening a workspace cleaned previously from all Metals and SBT build artifacts. The import succeeded, and Metals features seem to work in `zed` than.

**Comment by DGolubets** [comment]
Ok, that was $PATH problem.
I didn't pay attention to what Coursier told me about adding it's bin directory to $PATH.
Thanks everyone!
