### ISSUE TITLE
evaluation result in worksheet is not virtual text

### ISSUE THREAD

**Issue by dragove** [scalameta/metals-zed#23]
Steps to Reproduce:

1. create a file named `demo.worksheet.sc`
2. write a number inside this file e.g. `1`
3. the content becomes: `1 /*>  : Int = 1  */`

Expected Behavior:

the content remains `1` and the result `: Int = 1` should be a virtual text which can not be selected and not written in file.

**Comment by tgodzik** [comment]
Thanks for raising this! We have a custom extension for this that is not supported by the zed extension yet. Although, we will probably instead switch to inline values, which might be supported by zed at some point (if not already)

**Comment by tgodzik** [comment]
Some work on that is done in https://github.com/scalameta/metals/pull/6827/files
