### ISSUE TITLE
Diagnostics do not update on save

### ISSUE THREAD

**Issue by jakcharvat** [scalameta/metals-zed#28]
It appears my project doesn't recompile when I save the source files in an sbt project. As a result, only treesitter errors seem to update with the source, but not build diagnostics.

**Reproduction steps:**
- Create a new scala 3 project with `sbt new scala/scala3.g8`
- Open the project in zed, and open `Main.scala` in the editor
- Delete the `msg` `def`
  - Diagnostics do not update
 
- Restart the language server using `editor: restart language server`
  - `bloop: Not found: msg` diagnostic appears as expected

- Bring `def msg = ...` back
  - The project is compilable and runnable with sbt, but the `bloop: Not found: msg` error remains until the next language server restart

--- 

Looking at lsp and bsp traces from metals-nvim, it appears to send a `buildTarget/compile` request on file saves, which eventually results in a `build/publishDiagnostics` response. The zed extension seems to send no such request, and diagnostics only update on language server (re)start.

It seems like I am able to force recompile the project using the "clean compile" button in the web interface of the server, or by manually restarting the language server using zed's `editor: restart language server` command, but neither of those is very ergonomic. 

Am I the only one experiencing this issue? I have metals set up through coursier, using sbt to create projects. Zed metals settings only enable http server:
```json
"metals": {
  "binary": {
    "arguments": ["-Dmetals.http=on"]
  },
  "initialization_options": {
    "isHttpEnabled": true
  }
}
```

Doctor output:
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/81f11eea-d89b-47d8-92d7-012bdefe7003">

**Comment by tgodzik** [comment]
We should be getting didSave notifications when saving the file in Zed, which in turn should invoke the compilation. Are you able to check the .metals/lsp.trace.json file if that happens? If you create the file it should get polluted with traces

**Comment by jakcharvat** [comment]
Actually I'm not getting any traces there. When I make a bsp.trace.json I get a single `build/initialize` request with no response, but the lsp.trace.json file stays empty. 

The LSP features like goto definition, hovers, etc all work though, and I see their messages in the zed LSP Logs / RPC messages view. No didSave notifications there either though. 

This is the only entry I get in bsp.trace.json:
```json
[Trace - 05:27:01 PM] Sending request 'build/initialize - (1)'
Params: {
  "displayName": "Metals",
  "version": "1.3.5",
  "bspVersion": "2.2.0-M2",
  "rootUri": "file:///.../testproj/",
  "capabilities": {
    "languageIds": [
      "scala",
      "java"
    ],
    "jvmCompileClasspathReceiver": true
  },
  "data": {
    "javaSemanticdbVersion": "0.10.0",
    "semanticdbVersion": "4.9.9",
    "supportedScalaVersions": [
      "2.13.14",
      "2.12.19",
      "2.12.18",
      "2.12.17",
      "2.12.16",
      "2.13.11",
      "2.13.12",
      "2.13.13",
      "2.11.12"
    ],
    "enableBestEffortMode": false
  }
}
```

**Comment by jakcharvat** [comment]
Looks like zed was somehow interfering with the log files, just watching it with tail I do get messages in the lsp trace, but no didSave notifications. 

<details><summary>Here's the trace for opening a file, removing the `msg` method, saving and closing the file from the reproduction steps in the original post</summary>
<p>

```json
[Trace - 05:40:20 PM] Received notification 'textDocument/didOpen'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala",
    "languageId": "scala",
    "version": 0,
    "text": "@main def hello(): Unit \u003d\n  println(\"Hello world!\")\n  println(msg)\n\ndef msg: String \u003d \"Hello, World!\"\n"
  }
}


[Trace - 05:40:20 PM] Received request 'textDocument/inlayHint - (121)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 5,
      "character": 0
    }
  }
}


[Trace - 05:40:20 PM] Received request 'textDocument/documentHighlight - (122)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "position": {
    "line": 0,
    "character": 0
  }
}


[Trace - 05:40:20 PM] Sending response 'textDocument/documentHighlight - (122)'. Processing request took 7ms
Result: [
  {
    "range": {
      "start": {
        "line": 0,
        "character": 0
      },
      "end": {
        "line": 0,
        "character": 5
      }
    },
    "kind": 2
  }
]


[Trace - 05:40:20 PM] Received request 'textDocument/codeAction - (123)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 0
    }
  },
  "context": {
    "diagnostics": [],
    "only": [
      "quickfix",
      "refactor",
      "source.organizeImports"
    ]
  }
}


[Trace - 05:40:20 PM] Sending response 'textDocument/codeAction - (123)'. Processing request took 38ms
Result: [
  {
    "title": "Organize imports",
    "kind": "source.organizeImports",
    "diagnostics": [],
    "edit": {
      "changes": {
        "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala": []
      }
    }
  }
]


[Trace - 05:40:21 PM] Received request 'textDocument/documentHighlight - (124)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "position": {
    "line": 4,
    "character": 23
  }
}


[Trace - 05:40:21 PM] Sending response 'textDocument/documentHighlight - (124)'. Processing request took 3ms
Result: []


[Trace - 05:40:21 PM] Received request 'textDocument/documentHighlight - (125)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "position": {
    "line": 4,
    "character": 24
  }
}


[Trace - 05:40:21 PM] Sending response 'textDocument/documentHighlight - (125)'. Processing request took 3ms
Result: []


[Trace - 05:40:21 PM] Received request 'textDocument/documentHighlight - (126)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "position": {
    "line": 3,
    "character": 0
  }
}


[Trace - 05:40:21 PM] Sending response 'textDocument/documentHighlight - (126)'. Processing request took 2ms
Result: []


[Trace - 05:40:21 PM] Received request 'textDocument/codeAction - (127)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "range": {
    "start": {
      "line": 3,
      "character": 0
    },
    "end": {
      "line": 4,
      "character": 24
    }
  },
  "context": {
    "diagnostics": [],
    "only": [
      "quickfix",
      "refactor",
      "source.organizeImports"
    ]
  }
}


[Trace - 05:40:21 PM] Sending response 'textDocument/codeAction - (127)'. Processing request took 25ms
Result: [
  {
    "title": "Organize imports",
    "kind": "source.organizeImports",
    "diagnostics": [],
    "edit": {
      "changes": {
        "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala": []
      }
    }
  }
]


[Trace - 05:40:22 PM] Received notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 1,
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "contentChanges": [
    {
      "text": "@main def hello(): Unit \u003d\n  println(\"Hello world!\")\n  println(msg)\n"
    }
  ]
}


[Trace - 05:40:22 PM] Sending notification 'textDocument/publishDiagnostics'
Params: {
  "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala",
  "diagnostics": []
}


[Trace - 05:40:22 PM] Received request 'textDocument/documentHighlight - (128)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "position": {
    "line": 3,
    "character": 0
  }
}


[Trace - 05:40:22 PM] Sending response 'textDocument/documentHighlight - (128)'. Processing request took 8ms
Result: []


[Trace - 05:40:22 PM] Received request 'textDocument/codeAction - (129)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "range": {
    "start": {
      "line": 3,
      "character": 0
    },
    "end": {
      "line": 3,
      "character": 0
    }
  },
  "context": {
    "diagnostics": [],
    "only": [
      "quickfix",
      "refactor",
      "source.organizeImports"
    ]
  }
}


[Trace - 05:40:22 PM] Sending response 'textDocument/codeAction - (129)'. Processing request took 39ms
Result: [
  {
    "title": "Organize imports",
    "kind": "source.organizeImports",
    "diagnostics": [],
    "edit": {
      "changes": {
        "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala": []
      }
    }
  }
]


[Trace - 05:40:22 PM] Received request 'textDocument/formatting - (130)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "options": {
    "tabSize": 2,
    "insertSpaces": true,
    "trimTrailingWhitespace": true,
    "insertFinalNewline": true,
    "trimFinalNewlines": true
  }
}


[Trace - 05:40:22 PM] Sending response 'textDocument/formatting - (130)'. Processing request took 12ms
Result: []


[Trace - 05:40:22 PM] Received request 'textDocument/inlayHint - (131)'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 3,
      "character": 0
    }
  }
}


[Trace - 05:40:22 PM] Received notification '$/cancelRequest'
Params: {
  "id": 121
}


[Trace - 05:40:22 PM] Sending response 'textDocument/inlayHint - (121)'. Processing request took 2693ms
Result: null


[Trace - 05:40:25 PM] Received notification '$/cancelRequest'
Params: {
  "id": 131
}


[Trace - 05:40:25 PM] Sending response 'textDocument/inlayHint - (131)'. Processing request took 2741ms
Result: null


[Trace - 05:40:25 PM] Received notification 'textDocument/didClose'
Params: {
  "textDocument": {
    "uri": "file:///Users/jakcharvat/FIT/OOP/testproj/src/main/scala/Main.scala"
  }
}
```

</p>
</details>

**Comment by tgodzik** [comment]
That's unexpected, any idea if that is on purpose? we do depend on didSave notification

**Comment by jakcharvat** [comment]
Could it be related to https://github.com/zed-industries/zed/pull/14412?

**Comment by WeetHet** [comment]
It seems like zed thinks that watched paths for Metals are empty, weird

<img width="1093" alt="Screenshot 2024-10-13 at 21 38 35" src="https://github.com/user-attachments/assets/1bab8db6-76bb-4108-a50b-2aac8e2d3ab4">

**Comment by tgodzik** [comment]
Och, we do use our own watchers for most of the stuff, since we had worse experience with in build VS Code ones previously. We could add all Scala paths for Zed at least, though not sure we want to add them in general, which is a much bigger change.

Though I don't believe only watched files should be sent if they are indeed open. At least this is not the experience in other editors,

**Comment by filipwiech** [comment]
Hey, I'm terribly sorry, due to the lack of time I have completely forgot to link this issue here:
https://github.com/zed-industries/zed/issues/18636
You can find more details there and a linked change that explains the source of the problem. We need 2 things to fix this:
* First and foremost, Metals has to register more globs for file watching, basically to over all the Scala and Java source code in the workspace, not only a few special build files.
* We have to switch the default glob syntax to a VS Code one to get rid of the `file://` prefix. One can already do it with a custom Zed config like this one:
```json
"lsp": {
    "metals": {
      "initialization_options": {
        "globSyntax": "vscode"
      }
    }
  }
```

Hope that helps. :+1:

**Comment by WeetHet** [comment]
I've looked a bit into `fifSave`, and I'm unsure if textDocument/didSave should only be sent to the language servers watching the saved file. The spec is unclear, and, for example, helix sends it to everyone

If someone is better than me at reading VSCode files, here's the impl for VSCode, as far as I see it also send the notification to all servers

https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/textSynchronization.ts#L580

**Comment by tgodzik** [comment]
We also have `didChangeWatchedFiles` notification which is normally what I assumed was decided by the globs.

**Comment by tgodzik** [comment]
I commented a bit on the issue in Zed and I feel like they arbitrarily decided that LSP spec is saying one thing without consulting anyone, which seems to be the root of the problem. We could try and switch file watching for Scala/Java files to use the default file watching, but I can't promise when it will be. I need to work on a release first

**Comment by tgodzik** [comment]
At a minimum I think we would be able to force a setting. 

Overall,  the option to declare files we are interested in would be good to have, but it is simply not there yet.

**Comment by WeetHet** [comment]
> Overall, the option to declare files we are interested in would be good to have, but it is simply not there yet.

I'd prefer that to be a part of the LSP and not a Zed-specific feature

**Comment by tgodzik** [comment]
Looks like it was fixed upstream
