### ISSUE TITLE
Is there a way to identify if this extension has detected the scala project?

### ISSUE THREAD

**Issue by FredericDesgreniers** [scalameta/metals-zed#3]
First off, super excited to see metals support for Zed, but I can't seem to get it to work

I installed this extension from within Zed but it doesn't seem to be providing any language server type assistance to the project. I'm confused if the extension is loaded / recognized the project at all

I installed metals via courrier (not from any prompt inside the editor, but from looking at the source code on here) already.

Is there a way to debug this? Or is the extension right now just minimal enough that I haven't noticed what it does?  

Screenshots:
I have the extension installed 
<img width="1511" alt="image" src="https://github.com/scalameta/metals-zed/assets/4965262/9b40a119-9153-4b77-b17a-ec9a183ca354">

But even doing something like `A.` doesn't provide any support (nor does any jump to definition, .. work) 
<img width="1511" alt="image" src="https://github.com/scalameta/metals-zed/assets/4965262/e26f7fb6-a54d-4bf5-bafd-eea97a4affea">

Version I'm on: 
<img width="853" alt="image" src="https://github.com/scalameta/metals-zed/assets/4965262/15fa0805-2c41-4f5b-9ab9-927ced713e50">

**Comment by nightscape** [comment]
Same issue here, and [on Reddit](https://www.reddit.com/r/ZedEditor/comments/1c24lmy/how_to_use_scala_in_zed/).
@hmemcpy did you get the extension working on your machine?

**Comment by matejcerny** [comment]
Hey guys @FredericDesgreniers, @nightscape, I had the same issue, but then I installed metals via `cs install metals` (before I installed it via `brew`) and the scala project was immediately detected.

<img width="403" alt="image" src="https://github.com/scalameta/metals-zed/assets/35267431/0e2e89e0-b7d4-4da0-9ea1-0741f3148f9d">

**Comment by nightscape** [comment]
Ah, I also have metals installed via brew. I was convinced that this should suffice. I'll try with coursier! Thanks for the pointer 😃

**Comment by ngbinh** [comment]
somehow it still doesn't work for me. Is there anything I can do to force it?

**Comment by nightscape** [comment]
@ngbinh I was successful by first importing the build in VS Code, fixing all errors reported by the Metals Doctor and then starting Zed again.

**Comment by davesmith00000** [comment]
I have the same problem. To the author's question, is there a way to see debug info? At the moment I can't even tell if it's trying to connect to metals or not.
